# Generated by Django 2.1.7 on 2020-08-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinjunior', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='laptop',
            field=models.CharField(max_length=10),
        ),
    ]
